
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run-shell ~/.tmux/plugins/tmux-code-time/code-time.tmux
set -g status-right #{project_time}

set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark'

bind C-p previous-window
bind C-n next-window
bind R source-file '~/.tmux.conf'

set -g focus-events on

setw -g aggressive-resize on

run '~/.tmux/plugins/tpm/tpm'
